version: "3.7"

services:
    mariadb:
        image: wodby/mariadb:10.6-3.23.1
        container_name: "${PROJECT_NAME}_mariadb"
        environment:
            MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
            MYSQL_DATABASE: $DB_NAME
            MYSQL_USER: $DB_USER
            MYSQL_PASSWORD: $DB_PASSWORD
        volumes:
            - ./mariadb-init:/docker-entrypoint-initdb.d
            - ./.mysql:/var/lib/mysql

    php:
        image: wodby/wordpress-php:8.2-dev-4.42.3
        container_name: "${PROJECT_NAME}_php"
        environment:
            PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
            DB_HOST: $DB_HOST
            DB_USER: $DB_USER
            DB_PASSWORD: $DB_PASSWORD
            DB_NAME: $DB_NAME
            PHP_FPM_USER: wodby
            PHP_FPM_GROUP: wodby
        volumes:
            - ./:/var/www/html

    nginx:
        image: wodby/nginx:1.23-5.29.1
        container_name: "${PROJECT_NAME}_nginx"
        depends_on:
            - php
        environment:
            NGINX_STATIC_OPEN_FILE_CACHE: "off"
            NGINX_ERROR_LOG_LEVEL: debug
            NGINX_BACKEND_HOST: php
            NGINX_VHOST_PRESET: wordpress
            NGINX_SERVER_ROOT: /var/www/html/web
            NGINX_WP_GOOGLE_XML_SITEMAP: 1
        volumes:
            - ./:/var/www/html
        labels:
            - "traefik.frontend.priority=1"
            - 'traefik.backend=${PROJECT_NAME}_nginx'
            - 'traefik.port=80'
            - 'traefik.base.frontend.rule=Host:${PROJECT_BASE_URL}'
            - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)"

    mailhog:
        image: mailhog/mailhog
        container_name: "${PROJECT_NAME}_mailhog"
        labels:
            - "traefik.http.services.${PROJECT_NAME}_mailhog.loadbalancer.server.port=8025"
            - "traefik.http.routers.${PROJECT_NAME}_mailhog.rule=Host(`mailhog.${PROJECT_BASE_URL}`)"

    pma:
        image: phpmyadmin/phpmyadmin
        container_name: "${PROJECT_NAME}_pma"
        environment:
            PMA_HOST: $DB_HOST
            PMA_USER: $DB_USER
            PMA_PASSWORD: $DB_PASSWORD
            PHP_UPLOAD_MAX_FILESIZE: 1G
            PHP_MAX_INPUT_VARS: 1G
        labels:
            - "traefik.http.routers.${PROJECT_NAME}_pma.rule=Host(`pma.${PROJECT_BASE_URL}`)"

    traefik:
        image: traefik:v2.0
        container_name: "${PROJECT_NAME}_traefik"
        command: --api.insecure=true --providers.docker
        ports:
            - '80:80'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
